# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"AuthSdk": "authSdk.ipynb",
         "auth": "authSdk.ipynb",
         "createUser": "authSdk.ipynb"}

modules = ["auth.py"]

doc_url = "https://thanakijwanavit.github.io/pynamoLogger/"

git_url = "https://github.com/thanakijwanavit/pynamologger/tree/master/"

def custom_doc_links(name): return None
